### ISSUE TITLE
Add support for a custom log handler

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-js#102]
Users should be able to receive logs from the AAT via a custom `LogHandler` provided in the builder/constructor of the `Subscriber` instance. Right now we only accept `LoggerOptions` that configure the default logger that prints to the console. Instead, the users should provide a function that will be called whenever AAT needs to log a message. Then the users can choose what to do with the message (print it to the console, log it in some external errors tracker, etc.).

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2612) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Closing as this is already completed, the JS asset subscriber allows passing in arbitrary ably-js client options
