### ISSUE TITLE
Ably SDK ClientOptions are exposed in the API

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-js#103]
We are exposing the `ClientOptions` from the `ably-js` in our AAT API. On Android and iOS, we tend to not expose anything Ably-related in our API so perhaps we should do it as well in this project. If yes, then we need to create our custom type that would allow the users to configure only the required amount of options from the whole Ably's `ClientOptions`.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2611) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
This is intentional. I believe the decision to not expose ClientOptions in iOS and android asset tracking libraries was driven by what was idiomatic for the programming language, however no such restriction applies for the JS lib
