### ISSUE TITLE
Tracking ID is not provided in the builder/constructor

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-js#105]
On Android and iOS, the `trackableId` is provided in the `Subscriber` builder. Here, it is provided in the `start()` method after the instance is created. I'm not sure if that's a bad thing but it's inconsistent with the other platforms.

Relates to https://github.com/ably/ably-asset-tracking-js/issues/104

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2609) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
This is another side effect of the way we chose to design the JS subscriber SDK, it's inconsistent with other platforms but more idiomatic for JS (and allows the possibility of multiple assets on one ably connection which has been a features request for the JS SDK)
