### ISSUE TITLE
Accept skipped locations from the Publisher

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-js#33]
After merging this [Android PR](https://github.com/ably/ably-asset-tracking-android/pull/292) we are sending skipped locations as a part of the `LocationUpdate` messages. The js subscriber should be able to receive those skipped locations.

**Comment by kavalerov** [comment]
@QuintinWillison / @owenpearson is this something we can prioritise relatively soon on the JS side? And this milestone in general?
