### ISSUE TITLE
Add support for token based authentication 

### ISSUE THREAD

**Issue by kavalerov** [ably/ably-asset-tracking-js#49]
Provide the capability to authenticate users using Token Authentication.
See Android Issue and Android PR for more details.

Acceptance criteria:
- token request approach implemented

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-896) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Closing as we already support token authentication through `ablyOptions`
