### ISSUE TITLE
Move appropriate location rendering functional fro example app to the SDK

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-asset-tracking-js#76]
We need to move as much rendering functional from Subscriber app to the SDK because customers want to have a subscriber app as simple as possible and focus mostly on UI rather than location visualisation 
see https://github.com/ably/ably-asset-tracking-android/issues/632 as guidence

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1580) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
This is resolved by landing both https://github.com/ably/ably-asset-tracking-js/pull/84 and https://github.com/ably/ably-asset-tracking-js/pull/85, therefore, I'm closing this issue.
